[package]
name = "rust_rl"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.1"
actix-web = "4.11.0"
serde = { version = "1.0.219", features = ["derive"] }
actix-cors = "0.7.1"
indicatif = "0.17.11"
ordered-float = "5.0.0"
serde_json = "1.0"
plotters = "0.3.7"
